baseurl      = "https://quantumgarbage.com"
title        = "Quantum Garbage"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 10
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  
  
  # Subtitle for home
  homeSubtitle = "The whole world is garbage."

  enableThemeToggle = true
  # Enable sharing buttons, if you like
  enableSharingButtons = true

  # Metadata mostly used in document's head
  description = "A CS Student's blog."
  keywords = "homepage, blog"
  images = [""]

[author]
  name = "F.M. Bellomy"

[taxonomies]
  category = "blog"
  tag      = "tags"
  series   = "series"

[languages]
  [languages.en]
    title = "Quantum Garbage"
    subtitle = "A CS Student's blog."
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

  [params.footer]
    trademark = true
    rss = false
    copyright = true
    author = true

    topText = []
    bottomText = [
      "Powered by <a href=\"http://gohugo.io\">Hugo</a>",
    ]

    [languages.en.params.logo]
      logoMark = "$"
      logoText = "quantumgarbage"
      logoHomeLink = "/"
      logoCursorDisabled = "true"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts"
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "about"
